import {
  Ambulance,
  Anchor,
  Baby,
  Bell,
  Briefcase,
  Building,
  Bus,
  Car,
  Cloud,
  Contact,
  Cross,
  Dog,
  Droplet,
  Flame,
  GraduationCap,
  Heart,
  HeartPulse,
  Home,
  Hospital,
  Key,
  Lightbulb,
  MapPin,
  MoreHorizontal,
  Phone,
  Pill,
  Plug,
  School,
  Shield,
  ShoppingCart,
  Siren,
  Star,
  Stethoscope,
  Thermometer,
  Truck,
  Users,
  Utensils,
  Wallet,
  Wifi,
  Wrench,
  Zap,
  type LucideIcon,
} from "lucide-react";

export const CATEGORY_ICON_MAP: Record<string, LucideIcon> = {
  // Emergency & medical
  siren: Siren,
  shield: Shield,
  flame: Flame,
  cross: Cross,
  ambulance: Ambulance,
  hospital: Hospital,
  stethoscope: Stethoscope,
  heart: Heart,
  "heart-pulse": HeartPulse,
  thermometer: Thermometer,
  pill: Pill,
  // People & family
  users: Users,
  contact: Contact,
  baby: Baby,
  dog: Dog,
  // Home & places
  home: Home,
  building: Building,
  school: School,
  "graduation-cap": GraduationCap,
  "map-pin": MapPin,
  // Transport
  car: Car,
  bus: Bus,
  truck: Truck,
  anchor: Anchor,
  // Utilities & repair
  wrench: Wrench,
  droplet: Droplet,
  plug: Plug,
  key: Key,
  lightbulb: Lightbulb,
  wifi: Wifi,
  // Work & money
  briefcase: Briefcase,
  wallet: Wallet,
  "shopping-cart": ShoppingCart,
  utensils: Utensils,
  // Everything else
  bell: Bell,
  star: Star,
  cloud: Cloud,
  zap: Zap,
  more: MoreHorizontal,
};

export function categoryIcon(key: string): LucideIcon {
  return CATEGORY_ICON_MAP[key] ?? MoreHorizontal;
}
